### ISSUE TITLE
Error compiling Skyline && Future development

### ISSUE THREAD

**Issue by crqrdotcom** [hansonkd/skyline#2]
Hello,

Before anything, thanks for Skyline, as it seems already a nice project and will make my life much easier as I'm starting a project which uses MQTT and I'm starting learning more about it and how to use it...

I just added Skyline as a dependency on my app and, when compiling, I'm getting the following error:

```
== Compilation error in file lib/session.ex ==
** (CompileError) lib/session.ex:12: you must require Amnesia.Helper before invoking the macro Amnesia.Helper.result/1
    expanding macro: Amnesia.transaction/1
    lib/session.ex:12: Skyline.Session.start_session/1
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
could not compile dependency :skyline, "mix compile" failed. You can recompile this dependency with "mix deps.compile skyline", update it with "mix deps.update skyline" or clean it with "mix deps.clean skyline"
```

It seems pretty obvious and I'll probably submit a PR to fix it in the next few minutes.

I'd just like to know if you plan to keep developing this project, as it seems that there's no progress in the last few months... Maybe we could join forces if you would help me to better understand the library and MQTT in general!

Thank you in advance! Have a nice day!

**Comment by und0ck3d** [comment]
After fixing the above mentioned issue, another one happens:

```
...
Generated skyline app
==> my_broker
Compiling 1 file (.ex)
Generated my_broker app

15:18:58.967 [error] Process #PID<0.719.0> raised an exception
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.arguments/1
    (socket) lib/socket.ex:170: anonymous fn({:reuseaddr, true}) in Socket.arguments/1
    (elixir) lib/enum.ex:988: Enum.flat_map_list/2
    (elixir) lib/enum.ex:989: Enum.flat_map_list/2
    (socket) lib/socket/tcp.ex:285: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:163: Socket.TCP.listen/2
    (socket) lib/socket/tcp.ex:171: Socket.TCP.listen!/2
    (skyline) lib/acceptor.ex:21: Skyline.Acceptor.init/2

15:18:58.968 [error] Process #PID<0.721.0> raised an exception
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.arguments/1
    (socket) lib/socket.ex:170: anonymous fn({:reuseaddr, true}) in Socket.arguments/1
    (elixir) lib/enum.ex:988: Enum.flat_map_list/2
    (elixir) lib/enum.ex:989: Enum.flat_map_list/2
    (socket) lib/socket/tcp.ex:285: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:163: Socket.TCP.listen/2
    (socket) lib/socket/tcp.ex:171: Socket.TCP.listen!/2
    (skyline) lib/acceptor.ex:21: Skyline.Acceptor.init/2

15:18:58.968 [error] Process #PID<0.722.0> raised an exception
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.arguments/1
    (socket) lib/socket.ex:170: anonymous fn({:reuseaddr, true}) in Socket.arguments/1
    (elixir) lib/enum.ex:988: Enum.flat_map_list/2
    (elixir) lib/enum.ex:989: Enum.flat_map_list/2
    (socket) lib/socket/tcp.ex:285: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:163: Socket.TCP.listen/2
    (socket) lib/socket/tcp.ex:171: Socket.TCP.listen!/2
    (skyline) lib/acceptor.ex:21: Skyline.Acceptor.init/2

15:18:58.968 [error] Process #PID<0.723.0> raised an exception
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.arguments/1
    (socket) lib/socket.ex:170: anonymous fn({:reuseaddr, true}) in Socket.arguments/1
    (elixir) lib/enum.ex:988: Enum.flat_map_list/2
    (elixir) lib/enum.ex:989: Enum.flat_map_list/2
    (socket) lib/socket/tcp.ex:285: Socket.TCP.arguments/1
    (socket) lib/socket/tcp.ex:163: Socket.TCP.listen/2
    (socket) lib/socket/tcp.ex:171: Socket.TCP.listen!/2
    (skyline) lib/acceptor.ex:21: Skyline.Acceptor.init/2
```

Also, I was going to run the example application present in this repo, but it seems it depends on a local project that I can't find anywhere online... Could you give more info on that?

This is the output from running the example:

```
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:11

Unchecked dependencies for environment dev:
* skyline (../../spotmq/)
  the dependency is not available
** (Mix) Can't continue due to errors on dependencies
```

**Comment by und0ck3d** [comment]
Regarding the first error it was because I forgot to run `mix skyline.create_db`, sorry for that one!
